// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysql

import (
	"database/sql"
	"time"
)

// モンスターの基本情報
type Monster struct {
	// モンスターID(UUID)
	Monsterid string `json:"monsterid"`
	// ニックネーム
	Nickname string `json:"nickname"`
	// 元のゴミ箱の画像URL
	Originaltrashbinimageurl string `json:"originaltrashbinimageurl"`
	// 生成したモンスターの画像URL
	Generatedmonsterimageurl string `json:"generatedmonsterimageurl"`
	// 緯度(-90.0 ~ 90.0)
	Latitude sql.NullString `json:"latitude"`
	// 経度(-180.0 ~ 180.0)
	Longitude sql.NullString `json:"longitude"`
	// 作成日時
	Createdat time.Time `json:"createdat"`
	// 更新日時
	Updatedat time.Time `json:"updatedat"`
}

// モンスターの属性情報
type Monsterattribute struct {
	// モンスターID(UUID)
	Monsterid string `json:"monsterid"`
	// 属性の名前
	Attributename string `json:"attributename"`
	// カラーコード
	Colorcode string `json:"colorcode"`
	// 作成日時
	Createdat time.Time `json:"createdat"`
	// 更新日時
	Updatedat time.Time `json:"updatedat"`
}

// モンスターのゴミ種別(多対多)
type Monstertrashcategory struct {
	// モンスターゴミ種別ID(UUID)
	Monstertrashcategoryid string `json:"monstertrashcategoryid"`
	// モンスターID(UUID)
	Monsterid string `json:"monsterid"`
	// ゴミ種別(0:指定なし, 1:燃えるゴミ, 2:不燃ごみ, 3:缶, 4:瓶, 5:ペットボトル)
	Trashcategory uint8 `json:"trashcategory"`
	// 作成日時
	Createdat time.Time `json:"createdat"`
	// 更新日時
	Updatedat time.Time `json:"updatedat"`
}

// ユーザーの基本情報
type User struct {
	// ユーザーID(UUID)
	Userid string `json:"userid"`
	// ニックネーム
	Nickname string `json:"nickname"`
	// 作成日時
	Createdat time.Time `json:"createdat"`
	// 更新日時
	Updatedat time.Time `json:"updatedat"`
}
