// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monster_attribute.sql

package mysql

import (
	"context"
	"database/sql"
)

const createMonsterAttribute = `-- name: CreateMonsterAttribute :execresult
INSERT INTO MonsterAttribute (MonsterId, AttributeName, ColorCode)
VALUES (?, ?, ?)
`

type CreateMonsterAttributeParams struct {
	Monsterid     string `json:"monsterid"`
	Attributename string `json:"attributename"`
	Colorcode     string `json:"colorcode"`
}

func (q *Queries) CreateMonsterAttribute(ctx context.Context, arg CreateMonsterAttributeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMonsterAttribute, arg.Monsterid, arg.Attributename, arg.Colorcode)
}

const deleteMonsterAttribute = `-- name: DeleteMonsterAttribute :exec
DELETE FROM MonsterAttribute
WHERE MonsterId = ?
`

func (q *Queries) DeleteMonsterAttribute(ctx context.Context, monsterid string) error {
	_, err := q.db.ExecContext(ctx, deleteMonsterAttribute, monsterid)
	return err
}

const getMonsterAttribute = `-- name: GetMonsterAttribute :one
SELECT monsterid, attributename, colorcode, createdat, updatedat FROM MonsterAttribute
WHERE MonsterId = ? LIMIT 1
`

func (q *Queries) GetMonsterAttribute(ctx context.Context, monsterid string) (Monsterattribute, error) {
	row := q.db.QueryRowContext(ctx, getMonsterAttribute, monsterid)
	var i Monsterattribute
	err := row.Scan(
		&i.Monsterid,
		&i.Attributename,
		&i.Colorcode,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const updateMonsterAttribute = `-- name: UpdateMonsterAttribute :execresult
UPDATE MonsterAttribute
SET AttributeName = ?, ColorCode = ?
WHERE MonsterId = ?
`

type UpdateMonsterAttributeParams struct {
	Attributename string `json:"attributename"`
	Colorcode     string `json:"colorcode"`
	Monsterid     string `json:"monsterid"`
}

func (q *Queries) UpdateMonsterAttribute(ctx context.Context, arg UpdateMonsterAttributeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMonsterAttribute, arg.Attributename, arg.Colorcode, arg.Monsterid)
}
