// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mysql

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateMonster(ctx context.Context, arg CreateMonsterParams) (sql.Result, error)
	CreateMonsterAttribute(ctx context.Context, arg CreateMonsterAttributeParams) (sql.Result, error)
	CreateMonsterTrashCategory(ctx context.Context, arg CreateMonsterTrashCategoryParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteMonster(ctx context.Context, monsterid string) error
	DeleteMonsterAttribute(ctx context.Context, monsterid string) error
	DeleteMonsterTrashCategoriesByMonsterId(ctx context.Context, monsterid string) error
	DeleteMonsterTrashCategory(ctx context.Context, monstertrashcategoryid string) error
	DeleteUser(ctx context.Context, userid string) error
	GetMonster(ctx context.Context, monsterid string) (Monster, error)
	GetMonsterAttribute(ctx context.Context, monsterid string) (Monsterattribute, error)
	GetMonsterDetail(ctx context.Context, monsterid string) (GetMonsterDetailRow, error)
	GetMonsterTrashCategory(ctx context.Context, monstertrashcategoryid string) (Monstertrashcategory, error)
	GetUser(ctx context.Context, userid string) (User, error)
	ListMonsterTrashCategories(ctx context.Context, monsterid string) ([]Monstertrashcategory, error)
	ListMonsters(ctx context.Context) ([]Monster, error)
	ListMonstersByTrashCategory(ctx context.Context, trashcategory uint8) ([]Monstertrashcategory, error)
	ListMonstersWithAttribute(ctx context.Context) ([]ListMonstersWithAttributeRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateMonster(ctx context.Context, arg UpdateMonsterParams) (sql.Result, error)
	UpdateMonsterAttribute(ctx context.Context, arg UpdateMonsterAttributeParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
