// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package mysql

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO User (UserId, Nickname)
VALUES (?, ?)
`

type CreateUserParams struct {
	Userid   string `json:"userid"`
	Nickname string `json:"nickname"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Userid, arg.Nickname)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM User
WHERE UserId = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userid string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userid)
	return err
}

const getUser = `-- name: GetUser :one
SELECT userid, nickname, createdat, updatedat FROM User
WHERE UserId = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Nickname,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT userid, nickname, createdat, updatedat FROM User
ORDER BY CreatedAt DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.Nickname,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE User
SET Nickname = ?
WHERE UserId = ?
`

type UpdateUserParams struct {
	Nickname string `json:"nickname"`
	Userid   string `json:"userid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser, arg.Nickname, arg.Userid)
}
