// Code generated by outorouter; DO NOT EDIT.
// This file provides a type-safe API client for Expo/React Native.

// ============================================================================
// Configuration
// ============================================================================

const DEFAULT_BASE_URL = "https://api.example.com";

export interface ApiClientConfig {
  baseUrl?: string;
  headers?: Record<string, string>;
  onRequest?: (config: RequestConfig) => RequestConfig | Promise<RequestConfig>;
  onResponse?: <T>(response: ApiResponse<T>) => ApiResponse<T> | Promise<ApiResponse<T>>;
  onError?: (error: ApiError) => void;
}

let globalConfig: ApiClientConfig = {
  baseUrl: DEFAULT_BASE_URL,
};

export function configureApiClient(config: ApiClientConfig): void {
  globalConfig = { ...globalConfig, ...config };
}

export function getApiClientConfig(): ApiClientConfig {
  return globalConfig;
}

// ============================================================================
// Types
// ============================================================================

export interface RequestConfig {
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: string;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
  headers: Headers;
}

export interface ApiErrorResponse {
  error: {
    error: string;
    message: string;
  };
}

export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    message: string,
    public readonly response?: Response
  ) {
    super(message);
    this.name = "ApiError";
  }
}

// ============================================================================
// Request/Response Type Definitions
// ============================================================================

// Define your request and response types here.
// These types should match your backend API models.

/** Health Check Endpoint */
export interface HealthzRequest {
  // TODO: Define request fields for Healthz
}

/** Health Check Endpoint */
export interface HealthzResponse {
  // TODO: Define response fields for Healthz
}

// ============================================================================
// Endpoint Path Definitions
// ============================================================================

export const Endpoints = {
  Healthz: "/healthz/v1/Healthz",
} as const;

export type EndpointPath = (typeof Endpoints)[keyof typeof Endpoints];

// ============================================================================
// Endpoint Type Mapping
// ============================================================================

/**
 * Maps endpoint paths to their request and response types.
 * This enables type inference when calling the API.
 */
export interface EndpointTypes {
  "/healthz/v1/Healthz": {
    request: HealthzRequest;
    response: HealthzResponse;
  };
}

// ============================================================================
// Type-Safe API Client
// ============================================================================

/**
 * Type-safe API client function.
 * The request and response types are automatically inferred from the endpoint path.
 *
 * @example
 * ```typescript
 * const response = await api(Endpoints.CreateUser, {
 *   display_name: "John Doe",
 *   email: "john@example.com",
 *   password: "secret123",
 * });
 * // response is typed as CreateUserResponse
 * console.log(response.data.user_id);
 * ```
 */
export async function api<P extends keyof EndpointTypes>(
  endpoint: P,
  request: EndpointTypes[P]["request"],
  options?: {
    headers?: Record<string, string>;
    signal?: AbortSignal;
  }
): Promise<ApiResponse<EndpointTypes[P]["response"]>> {
  const config = getApiClientConfig();
  const url = `${config.baseUrl ?? DEFAULT_BASE_URL}${endpoint}`;

  let requestConfig: RequestConfig = {
    method: "POST",
    url,
    headers: {
      "Content-Type": "application/json",
      ...config.headers,
      ...options?.headers,
    },
    body: JSON.stringify(request),
  };

  // Apply request interceptor
  if (config.onRequest) {
    requestConfig = await config.onRequest(requestConfig);
  }

  const fetchOptions: RequestInit = {
    method: requestConfig.method,
    headers: requestConfig.headers,
    body: requestConfig.body,
    signal: options?.signal,
  };

  const response = await fetch(requestConfig.url, fetchOptions);

  if (!response.ok) {
    let errorData: ApiErrorResponse | null = null;
    try {
      errorData = await response.json();
    } catch {
      // Response body is not JSON
    }

    const apiError = new ApiError(
      response.status,
      errorData?.error?.error ?? "UNKNOWN_ERROR",
      errorData?.error?.message ?? response.statusText,
      response
    );

    if (config.onError) {
      config.onError(apiError);
    }

    throw apiError;
  }

  const data = (await response.json()) as EndpointTypes[P]["response"];

  let result: ApiResponse<EndpointTypes[P]["response"]> = {
    data,
    status: response.status,
    headers: response.headers,
  };

  // Apply response interceptor
  if (config.onResponse) {
    result = await config.onResponse(result);
  }

  return result;
}

// ============================================================================
// Convenience Hooks for React/Expo (Optional)
// ============================================================================

/**
 * Creates a typed API caller for a specific endpoint.
 * Useful for creating reusable API functions.
 *
 * @example
 * ```typescript
 * const createUser = createApiCaller(Endpoints.CreateUser);
 * const response = await createUser({ display_name: "John", email: "..." });
 * ```
 */
export function createApiCaller<P extends keyof EndpointTypes>(endpoint: P) {
  return (
    request: EndpointTypes[P]["request"],
    options?: {
      headers?: Record<string, string>;
      signal?: AbortSignal;
    }
  ) => api(endpoint, request, options);
}

// ============================================================================
// Pre-configured API Callers
// ============================================================================

export const apiCallers = {
  /** Health Check Endpoint */
  Healthz: createApiCaller(Endpoints.Healthz),
};
