package generator

import (
	"bytes"
	"sort"
	"text/template"

	"github.com/kinpatsu-everyone/backend-template/pkg/outorouter/internal/parser"
)

// GoTypeStrategy は Go 用のエンドポイント定義を生成する。
type GoTypeStrategy struct {
	PackageName string
}

func (s GoTypeStrategy) Name() string { return "go" }

func (s GoTypeStrategy) Generate(meta *parser.Metadata) (string, error) {
	if s.PackageName == "" {
		s.PackageName = "generated"
	}

	data := map[string]any{
		"Package":   s.PackageName,
		"Endpoints": sorted(meta.All),
	}

	buf := &bytes.Buffer{}
	tmpl := template.Must(template.New("goEndpoints").Parse(goTemplate))
	if err := tmpl.Execute(buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const goTemplate = `// Code generated by outorouter parser; DO NOT EDIT.
package {{.Package}}

type EndpointDescriptor struct {
	Method       string
	Path         string
	RequestType  string
	ResponseType string
	Summary      string
	Tags         []string
}

var Endpoints = []EndpointDescriptor{
{{- range .Endpoints }}
	{
		Method: "{{ .HTTPMethod }}",
		Path: "{{ .Path }}",
		RequestType: "{{ .RequestType }}",
		ResponseType: "{{ .ResponseType }}",
		Summary: "{{ .Summary }}",
		Tags: []string{ {{- range $i, $t := .Tags }}{{if $i}}, {{end}}"{{$t}}"{{end}} },
	},
{{- end }}
}
`

func sorted(eps []parser.Endpoint) []parser.Endpoint {
	res := make([]parser.Endpoint, len(eps))
	copy(res, eps)
	sort.Slice(res, func(i, j int) bool { return res[i].Path() < res[j].Path() })
	return res
}
