package generator

import (
	"bytes"
	"text/template"

	"github.com/kinpatsu-everyone/backend-template/pkg/outorouter/internal/parser"
)

// TypeScriptStrategy は TypeScript の interface/Record 形式を生成する。
type TypeScriptStrategy struct{}

func (s TypeScriptStrategy) Name() string { return "typescript" }

func (s TypeScriptStrategy) Generate(meta *parser.Metadata) (string, error) {
	data := map[string]any{
		"Endpoints": sorted(meta.All),
	}

	buf := &bytes.Buffer{}
	tmpl := template.Must(template.New("tsEndpoints").Parse(tsTemplate))
	if err := tmpl.Execute(buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const tsTemplate = `// Code generated by outorouter parser; DO NOT EDIT.
export interface EndpointDescriptor {
  method: string;
  path: string;
  requestType: string;
  responseType: string;
  summary: string;
  tags: string[];
}

export const endpoints: Record<string, EndpointDescriptor> = {
{{- range .Endpoints }}
  "{{ .Path }}": {
    method: "{{ .HTTPMethod }}",
    path: "{{ .Path }}",
    requestType: "{{ .RequestType }}",
    responseType: "{{ .ResponseType }}",
    summary: "{{ .Summary }}",
    tags: [{{- range $i, $t := .Tags }}{{ if $i }}, {{ end }}"{{$t}}"{{ end }}],
  },
{{- end }}
};
`
