// Code generated by outorouter; DO NOT EDIT.
// This file provides a type-safe API client for Expo/React Native.

// ============================================================================
// Configuration
// ============================================================================

const DEFAULT_BASE_URL =
  'https://backend-api-713089770976.asia-northeast1.run.app';

export interface ApiClientConfig {
  baseUrl?: string;
  headers?: Record<string, string>;
  onRequest?: (config: RequestConfig) => RequestConfig | Promise<RequestConfig>;
  onResponse?: <T>(
    response: ApiResponse<T>
  ) => ApiResponse<T> | Promise<ApiResponse<T>>;
  onError?: (error: ApiError) => void;
}

let globalConfig: ApiClientConfig = {
  baseUrl: DEFAULT_BASE_URL,
};

export function configureApiClient(config: ApiClientConfig): void {
  globalConfig = { ...globalConfig, ...config };
}

export function getApiClientConfig(): ApiClientConfig {
  return globalConfig;
}

// ============================================================================
// Types
// ============================================================================

export interface RequestConfig {
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: string;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
  headers: Headers;
}

export interface ApiErrorResponse {
  error: {
    error: string;
    message: string;
  };
}

export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly code: string,
    message: string,
    public readonly response?: Response
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

// ============================================================================
// Nested Type Definitions
// ============================================================================

/** Nested type: CandidateResponse */
export interface CandidateResponse {
  content: ContentResponse;
  finish_reason?: string;
}

/** Nested type: ContentResponse */
export interface ContentResponse {
  role: string;
  parts: PartResponse[];
}

/** Nested type: PartResponse */
export interface PartResponse {
  text?: string;
  image_data?: ImageData;
  file_data?: FileData;
}

/** Nested type: ImageData */
export interface ImageData {
  mime_type: string;
  data: string;
}

/** Nested type: FileData */
export interface FileData {
  mime_type: string;
  file_uri: string;
}

/** Nested type: MonsterItem */
export interface MonsterItem {
  id: string;
  nickname: string;
  latitude: number;
  longitude: number;
  trash_category: string;
  image_url: string;
}

// ============================================================================
// Request/Response Type Definitions
// ============================================================================

/** Analyze Trash Bin and Generate Monster Character (Multipart) - Request */
export interface AnalyzeAndGenerateImageRequest {
  image: FileHeader;
  model: string;
}

/** Analyze Trash Bin and Generate Monster Character (Multipart) - Response */
export interface AnalyzeAndGenerateImageResponse {
  image_data: string;
  mime_type: string;
}

/** Analyze Image using Gemini - Request */
export interface AnalyzeImageRequest {
  image_data: string;
  mime_type?: string;
  model?: string;
}

/** Analyze Image using Gemini - Response */
export interface AnalyzeImageResponse {
  text: string;
}

/** Generate Image using Gemini 3 Pro Image - Request */
export interface GenerateImageRequest {
  prompt: string;
  model?: string;
}

/** Generate Image using Gemini 3 Pro Image - Response */
export interface GenerateImageResponse {
  candidates: CandidateResponse[];
}

/** Health Check Endpoint - Request */
export interface HealthzRequest {
  // Empty request
}

/** Health Check Endpoint - Response */
export interface HealthzResponse {
  version: string;
  status: string;
  message: string;
}

/** Create Monster - Request */
export interface CreateMonsterRequest {
  nickname: string;
  latitude: number;
  longitude: number;
  image: FileHeader;
}

/** Create Monster - Response */
export interface CreateMonsterResponse {
  monsterid: string;
}

/** Get Monster - Request */
export interface GetMonsterRequest {
  id: string;
}

/** Get Monster - Response */
export interface GetMonsterResponse {
  monster: MonsterItem;
}

/** Get Monsters - Request */
export interface GetMonstersRequest {
  // Empty request
}

/** Get Monsters - Response */
export interface GetMonstersResponse {
  monsters: MonsterItem[];
}

// ============================================================================
// Endpoint Path Definitions
// ============================================================================

export const Endpoints = {
  AnalyzeAndGenerateImage: '/gemini/v1/AnalyzeAndGenerateImage',
  AnalyzeImage: '/gemini/v1/AnalyzeImage',
  GenerateImage: '/gemini/v1/GenerateImage',
  Healthz: '/healthz/v1/Healthz',
  CreateMonster: '/monster/v1/CreateMonster',
  GetMonster: '/monster/v1/GetMonster',
  GetMonsters: '/monster/v1/GetMonsters',
} as const;

export type EndpointPath = (typeof Endpoints)[keyof typeof Endpoints];

// ============================================================================
// Endpoint Type Mapping
// ============================================================================

/**
 * Maps endpoint paths to their request and response types.
 * This enables type inference when calling the API.
 */
export interface EndpointTypes {
  '/gemini/v1/AnalyzeAndGenerateImage': {
    request: AnalyzeAndGenerateImageRequest;
    response: AnalyzeAndGenerateImageResponse;
  };
  '/gemini/v1/AnalyzeImage': {
    request: AnalyzeImageRequest;
    response: AnalyzeImageResponse;
  };
  '/gemini/v1/GenerateImage': {
    request: GenerateImageRequest;
    response: GenerateImageResponse;
  };
  '/healthz/v1/Healthz': {
    request: HealthzRequest;
    response: HealthzResponse;
  };
  '/monster/v1/CreateMonster': {
    request: CreateMonsterRequest;
    response: CreateMonsterResponse;
  };
  '/monster/v1/GetMonster': {
    request: GetMonsterRequest;
    response: GetMonsterResponse;
  };
  '/monster/v1/GetMonsters': {
    request: GetMonstersRequest;
    response: GetMonstersResponse;
  };
}

// ============================================================================
// Type-Safe API Client
// ============================================================================

/**
 * Type-safe API client function.
 * The request and response types are automatically inferred from the endpoint path.
 *
 * @example
 * ```typescript
 * const response = await api(Endpoints.CreateUser, {
 *   display_name: "John Doe",
 *   email: "john@example.com",
 *   password: "secret123",
 * });
 * // response is typed as CreateUserResponse
 * console.log(response.data.user_id);
 * ```
 */
export async function api<P extends keyof EndpointTypes>(
  endpoint: P,
  request: EndpointTypes[P]['request'],
  options?: {
    headers?: Record<string, string>;
    signal?: AbortSignal;
  }
): Promise<ApiResponse<EndpointTypes[P]['response']>> {
  const config = getApiClientConfig();
  const url = `${config.baseUrl ?? DEFAULT_BASE_URL}${endpoint}`;

  let requestConfig: RequestConfig = {
    method: 'POST',
    url,
    headers: {
      'Content-Type': 'application/json',
      ...config.headers,
      ...options?.headers,
    },
    body: JSON.stringify(request),
  };

  // Apply request interceptor
  if (config.onRequest) {
    requestConfig = await config.onRequest(requestConfig);
  }

  const fetchOptions: RequestInit = {
    method: requestConfig.method,
    headers: requestConfig.headers,
    body: requestConfig.body,
    signal: options?.signal,
  };

  const response = await fetch(requestConfig.url, fetchOptions);

  if (!response.ok) {
    let errorData: ApiErrorResponse | null = null;
    try {
      errorData = await response.json();
    } catch {
      // Response body is not JSON
    }

    const apiError = new ApiError(
      response.status,
      errorData?.error?.error ?? 'UNKNOWN_ERROR',
      errorData?.error?.message ?? response.statusText,
      response
    );

    if (config.onError) {
      config.onError(apiError);
    }

    throw apiError;
  }

  const data = (await response.json()) as EndpointTypes[P]['response'];

  let result: ApiResponse<EndpointTypes[P]['response']> = {
    data,
    status: response.status,
    headers: response.headers,
  };

  // Apply response interceptor
  if (config.onResponse) {
    result = await config.onResponse(result);
  }

  return result;
}

// ============================================================================
// Convenience Hooks for React/Expo (Optional)
// ============================================================================

/**
 * Creates a typed API caller for a specific endpoint.
 * Useful for creating reusable API functions.
 *
 * @example
 * ```typescript
 * const createUser = createApiCaller(Endpoints.CreateUser);
 * const response = await createUser({ display_name: "John", email: "..." });
 * ```
 */
export function createApiCaller<P extends keyof EndpointTypes>(endpoint: P) {
  return (
    request: EndpointTypes[P]['request'],
    options?: {
      headers?: Record<string, string>;
      signal?: AbortSignal;
    }
  ) => api(endpoint, request, options);
}

// ============================================================================
// Pre-configured API Callers
// ============================================================================

export const apiCallers = {
  /** Analyze Trash Bin and Generate Monster Character (Multipart) */
  AnalyzeAndGenerateImage: createApiCaller(Endpoints.AnalyzeAndGenerateImage),
  /** Analyze Image using Gemini */
  AnalyzeImage: createApiCaller(Endpoints.AnalyzeImage),
  /** Generate Image using Gemini 3 Pro Image */
  GenerateImage: createApiCaller(Endpoints.GenerateImage),
  /** Health Check Endpoint */
  Healthz: createApiCaller(Endpoints.Healthz),
  /** Create Monster */
  CreateMonster: createApiCaller(Endpoints.CreateMonster),
  /** Get Monster */
  GetMonster: createApiCaller(Endpoints.GetMonster),
  /** Get Monsters */
  GetMonsters: createApiCaller(Endpoints.GetMonsters),
};
